In [14]:
import numpy as np
import csv
import time

input_cnt, output_cnt = 10, 1
data = np.zeros([3, input_cnt + output_cnt])


print(np.random.normal(5,0.1,1100))
shuffle_map = np.arange(12)
print(shuffle_map)
np.random.shuffle(shuffle_map)
print(shuffle_map)

[5.16941032 5.13012154 4.84449199 ... 5.1361477  5.14269196 5.05819967]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  9  7  5  1 11  3  8  2 10  6]
